//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiLo.Lite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiLo.Lite.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alert...(coming soon).
        /// </summary>
        public static string AlertsComingSoonLabel {
            get {
                return ResourceManager.GetString("AlertsComingSoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ExitModalCancelText {
            get {
                return ResourceManager.GetString("ExitModalCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string ExitModalMessage {
            get {
                return ResourceManager.GetString("ExitModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ExitModalOkText {
            get {
                return ResourceManager.GetString("ExitModalOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        public static string ExitModalTitle {
            get {
                return ResourceManager.GetString("ExitModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No market feed data....
        /// </summary>
        public static string NoMarketDataLabel {
            get {
                return ResourceManager.GetString("NoMarketDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryLabel {
            get {
                return ResourceManager.GetString("RetryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for currency....
        /// </summary>
        public static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Style.
        /// </summary>
        public static string SettingsChartingLabelBarStyle {
            get {
                return ResourceManager.GetString("SettingsChartingLabelBarStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Indicator.
        /// </summary>
        public static string SettingsChartingLabelDefaultIndicator {
            get {
                return ResourceManager.GetString("SettingsChartingLabelDefaultIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Interval.
        /// </summary>
        public static string SettingsChartingLabelDefaultInterval {
            get {
                return ResourceManager.GetString("SettingsChartingLabelDefaultInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Tools Bar.
        /// </summary>
        public static string SettingsChartingLabelDrawingToolBar {
            get {
                return ResourceManager.GetString("SettingsChartingLabelDrawingToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage &gt;.
        /// </summary>
        public static string SettingsFavouriteManage {
            get {
                return ResourceManager.GetString("SettingsFavouriteManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Favourites.
        /// </summary>
        public static string SettingsFavouritesLabelUse {
            get {
                return ResourceManager.GetString("SettingsFavouritesLabelUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/GeorgeLeithead/LiLo.Lite.
        /// </summary>
        public static string SettingsGitHub {
            get {
                return ResourceManager.GetString("SettingsGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsHeadingAbout {
            get {
                return ResourceManager.GetString("SettingsHeadingAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charting.
        /// </summary>
        public static string SettingsHeadingCharting {
            get {
                return ResourceManager.GetString("SettingsHeadingCharting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string SettingsHeadingFavourites {
            get {
                return ResourceManager.GetString("SettingsHeadingFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsHeadingTheme {
            get {
                return ResourceManager.GetString("SettingsHeadingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsIconText {
            get {
                return ResourceManager.GetString("SettingsIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.internetwideworld.com/lilolite.
        /// </summary>
        public static string SettingsIww {
            get {
                return ResourceManager.GetString("SettingsIww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright George Leithead, Ver: {0}
        ///
        ///Please contact us on the social platform(s) below.  Please include the application information from above (version, release, etc.), your device details, a description of your problem and steps to replicate.  You can also just reach out and say &quot;hello&quot;..
        /// </summary>
        public static string SettingsLabelAbout {
            get {
                return ResourceManager.GetString("SettingsLabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SettingsTemeLabelSystem {
            get {
                return ResourceManager.GetString("SettingsTemeLabelSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsThemeLabelDark {
            get {
                return ResourceManager.GetString("SettingsThemeLabelDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsThemeLabelLight {
            get {
                return ResourceManager.GetString("SettingsThemeLabelLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/LiLoMobileApp.
        /// </summary>
        public static string SettingsTwitter {
            get {
                return ResourceManager.GetString("SettingsTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body class=&quot;X1X&quot;&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body { margin: 0; }
        ///.dark {
        ///	background-color: black;
        ///	color: white;
        ///}
        ///
        ///.light {
        ///	background-color: white;
        ///	color: black;
        ///}
        ///iframe.body {
        ///	-moz-transform:scale(0.75);
        ///	-moz-transform-origin: 0 0;
        ///	-o-transform: scale(0.75);
        ///	-o-transform-origin: 0 0;
        ///	-webkit-transform: scale(0.75);
        ///	-webkit-transform-origin: 0 0;
        ///}
        ///&lt;/style&gt;
        ///&lt;!-- TradingView Widget BEGIN --&gt;
        ///&lt;div class=&quot;tradingview-widget-container&quot;&gt;
        ///  &lt;div id=&quot;tradingview_lilo&quot;&gt;&lt;/div [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TradingViewPage {
            get {
                return ResourceManager.GetString("TradingViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string ViewTitleAlerts {
            get {
                return ResourceManager.GetString("ViewTitleAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string ViewTitleChart {
            get {
                return ResourceManager.GetString("ViewTitleChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favourites.
        /// </summary>
        public static string ViewTitleFavourites {
            get {
                return ResourceManager.GetString("ViewTitleFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string ViewTitleMarkets {
            get {
                return ResourceManager.GetString("ViewTitleMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ViewTitleSettings {
            get {
                return ResourceManager.GetString("ViewTitleSettings", resourceCulture);
            }
        }
    }
}
