name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls
        
  build:
    name: Setup Xamarin and Mono versions
    runs-on: macos-latest
    steps:
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: latest # specify version in '<major>.<minor>' format
        xamarin-ios-version: latest # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: latest # specify full version; it is not recommended option because your pipeline can be broken suddenly in future
        xcode-version: latest # set the latest available Xcode 11

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Android
      run: |
        cd source
        cd LiLo.Lite
        nuget restore
        sudo purge
        cd LiLo.Lite.Android
        msbuild LiLo.Lite.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  #iOS:
    #runs-on: macos-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: iOS
      #run: |
        #cd source
        #cd LiLo.Lite
        #nuget restore
        #cd LiLo.Lite.iOS
        #msbuild LiLo.Lite.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug