name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 5.6.x
    - name: Android
      run: |
        cd source
        cd LiLo.Lite
        nuget restore
        sudo purge
        cd LiLo.Lite.Android
        msbuild LiLo.Lite.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  #iOS:
    #runs-on: macos-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: iOS
      #run: |
        #cd source
        #cd LiLo.Lite
        #nuget restore
        #cd LiLo.Lite.iOS
        #msbuild LiLo.Lite.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug